---
- name: Push IOS Config
  ansible.builtin.include_tasks: ios.yml
  when: ansible_network_os == 'cisco.ios.ios'

- name: Push EOS Config
  ansible.builtin.include_tasks: eos.yml
  when: ansible_network_os == 'arista.eos.eos'

- name: Push VYOS Config
  ansible.builtin.include_tasks: vyos.yml
  when: ansible_network_os == 'vyos.vyos.vyos'
