collections:

  - name: vyos.vyos

  - name: cisco.ios

  - name: arista.eos

  - name: ansible.netcommon

  - name: ansible.tower

  - name: shadowman.reports
    source: https://towerhub.shadowman.dev/api/galaxy/content/published/