collections:

  - name: vyos.vyos
    version: 1.1.1

  - name: cisco.ios
    version: 1.3.0

  - name: arista.eos
    version: 1.3.0

  - name: ansible.netcommon
    version: 1.5.0

  - name: ansible.tower