---
- name: Configure hostname on ios
  cisco.ios.ios_hostname:
    config:
      hostname: "{{ inventory_hostname }}"

- name: Update l3 interfaces on ios
  cisco.ios.ios_l3_interfaces:
    state: overridden
    config:
      - name: GigabitEthernet1
        ipv4:
          - dhcp:
              enable: true
      - name: GigabitEthernet2
        ipv4:
          - address: "{{ gigabit2 }}/28"

- name: Update interfaces on ios
  cisco.ios.ios_interfaces:
    state: overridden
    config:
      - name: GigabitEthernet1
        description: "This is {{ configured_by }}"
        enabled: true
      - name: GigabitEthernet2
        description: "This is {{ configured_by }}"
        enabled: true

- name: Update lldp global on ios
  cisco.ios.ios_lldp_global:
    state: replaced
    config:
      holdtime: 10
      enabled: true
      timer: 10

- name: Update lacp interfaces on ios
  cisco.ios.ios_lacp_interfaces:
    config:
      - name: GigabitEthernet1
        port_priority: 10
      - name: GigabitEthernet2
        port_priority: 20
    state: overridden

- name: Update lldp interfaces on ios
  cisco.ios.ios_lldp_interfaces:
    state: overridden
    config:
      - name: GigabitEthernet1
        transmit: false
      - name: GigabitEthernet2
        transmit: false

- name: Set base static_routes on ios
  cisco.ios.ios_static_routes:
    config:
      - address_families:
          - afi: ipv4
            routes:
              - dest: 198.51.100.0/24
                next_hops:
                  - forward_router_address: 198.51.101.1
                    name: merged_route_1
                    distance_metric: 110
                    tag: 40
                    multicast: true
                  - forward_router_address: 198.51.101.2
                    name: merged_route_2
                    distance_metric: 30
                  - forward_router_address: 198.51.101.3
                    name: merged_route_3
    state: overridden
