---
- name: Perform IOS config
  ansible.builtin.include_tasks: ios.yml
  when: ansible_network_os == 'cisco.ios.ios'

- name: Perform EOS config
  ansible.builtin.include_tasks: eos.yml
  when: ansible_network_os == 'arista.eos.eos'

- name: Perform VYOS config
  ansible.builtin.include_tasks: vyos.yml
  when: ansible_network_os == 'vyos.vyos.vyos'
