---
- name: Backup eos device
  arista.eos.eos_config:
    backup: true
    backup_options:
      filename: "{{ lookup('pipe', 'date +%Y-%m-%d') }}.cfg"
      dir_path: /tmp/home/network/arista_backup/{{ inventory_hostname }}
  become: true
  register: config_output

- name: REMOVE username and password
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: username.*
    state: absent

- name: REMOVE enable name
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: enable.*
    state: absent

- name: Find all Arista backups
  ansible.builtin.find:
    paths: /tmp/home/network/arista_backup/{{ inventory_hostname }}
    recurse: true
  register: backups

- name: Delete oldest backup
  ansible.builtin.file:
    path: "{{ backups.files | sort(attribute='path') | map(attribute='path') | first }}"
    state: absent
  when: backups.files | length > 2
