---
- name: Backup ios device
  cisco.ios.ios_config:
    backup: true
    backup_options:
      filename: "{{ lookup('pipe', 'date +%Y-%m-%d') }}.cfg"
      dir_path: /tmp/home/network/cisco_backup/{{ inventory_hostname }}
  become: true
  register: config_output

- name: REMOVE NON CONFIG LINES - REGEXP
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    line: Building configuration...
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: Current configuration.*
    state: absent

- name: REMOVE enable password
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: enable password.*
    state: absent

- name: REMOVE username and password
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: username.*
    state: absent

- name: Find all Cisco backups
  ansible.builtin.find:
    paths: /tmp/home/network/cisco_backup/{{ inventory_hostname }}
    recurse: true
  register: backups

- name: Delete oldest backup
  ansible.builtin.file:
    path: "{{ backups.files | sort(attribute='path') | map(attribute='path') | first }}"
    state: absent
  when: backups.files | length > 2
