---
- name: Sync with Gitrepo      
  ansible.builtin.git:
    repo: 'git@github.com:shadowman-lab/Ansible-Networking.git'
    dest: /tmp/home/network
    force: yes
  delegate_to: aap.shadowman.dev

- name: Backup ios device
  cisco.ios.ios_config:
    backup: yes
    backup_options:
      dir_path: /tmp/home/network/backup
  become: yes
  register: config_output

- name: REMOVE NON CONFIG LINES - REGEXP
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    line: "Building configuration..."
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: 'Current configuration.*'
    state: absent

- name: REMOVE enable password
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: 'enable password.*'
    state: absent

- name: REMOVE username and password
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: 'username.*'
    state: absent

- name: Copy files to aap      
  ansible.builtin.copy:
    src: /tmp/home/network/backup
    dest: /tmp/home/network/
  delegate_to: aap.shadowman.dev

- name: Find backup files older than 7 days
  ansible.builtin.find:
    paths: /tmp/home/network/backup
    recurse: yes
    age: 7d
  register: old_backups
  delegate_to: aap.shadowman.dev

- name: Delete backup files older than 7 days
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_backups.files }}"
  loop_control:
    label: "{{ item.path }}"
  delegate_to: aap.shadowman.dev

- name: Update git repo with backup
  ansible.builtin.shell: git add -A && git commit -m "Synching new backup to repo" && git push
  args:
    chdir: /tmp/home/network
  delegate_to: aap.shadowman.dev