---
- name: Backup nxos device
  cisco.nxos.nxos_config:
    backup: true
    backup_options:
      filename: "{{ lookup('pipe', 'date +%Y-%m-%d') }}.cfg"
      dir_path: /tmp/home/network/nxos_backup/{{ inventory_hostname }}
  become: true
  register: config_output

- name: REMOVE NON CONFIG LINES - REGEXP
  ansible.builtin.lineinfile:
    path: /tmp/home/network/{{ inventory_hostname }}.cfg
    line: '!Command: show running-config'
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  ansible.builtin.lineinfile:
    path: /tmp/home/network/{{ inventory_hostname }}.cfg
    regexp: '!Running configuration last done at.*'
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  ansible.builtin.lineinfile:
    path: /tmp/home/network/{{ inventory_hostname }}.cfg
    regexp: '!Time.*'
    state: absent

- name: REMOVE username and password
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: username.*
    state: absent

- name: REMOVE SNMP user configuration
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: snmp-server user.*
    state: absent

- name: Find all NX-OS backups
  ansible.builtin.find:
    paths: /tmp/home/network/nxos_backup/{{ inventory_hostname }}
    recurse: true
  register: backups

- name: Delete oldest backup
  ansible.builtin.file:
    path: "{{ backups.files | sort(attribute='path') | map(attribute='path') | first }}"
    state: absent
  when: backups.files | length > 2
