---
- name: Sync with Gitrepo
  ansible.builtin.git:
    repo: git@github.com:shadowman-lab/Ansible-Networkingbackup.git
    dest: /tmp/home/network
    version: main
    accept_newhostkey: true
    key_file: "{{ cert_key_file }}"
  delegate_to: localhost
  run_once: true

- name: Backup vyos device
  vyos.vyos.vyos_config:
    backup: true
    backup_options:
      dir_path: /tmp/home/network/vyos_backup
  become: true
  register: config_output

- name: REMOVE encrypted password
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: set system login user vyos authentication encrypted-password.*
    state: absent

- name: REMOVE plaintext password
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: set system login user vyos authentication plaintext-password.*
    state: absent

- name: Update git repo with backup
  ansible.builtin.shell: git add -A && git commit -m "Synching new backup to repo" && git config --global core.sshCommand 'ssh -i {{ cert_key_file }} -F /dev/null'
    && git push
  args:
    chdir: /tmp/home/network
  environment:
    GIT_COMMITTER_NAME: "{{ git_name | default(omit) }}"
    GIT_COMMITTER_EMAIL: "{{ git_email | default(omit) }}"
    GIT_AUTHOR_NAME: "{{ git_name | default(omit) }}"
    GIT_AUTHOR_EMAIL: "{{ git_email | default(omit) }}"
  run_once: true
  delegate_to: localhost
