---
- name: Add hosts to F5 Load Balancer
  hosts: "{{ vm_name | default('all') }}"
  gather_facts: false

  vars:
    pool_name: https_pool
    virtual_server_name: webapp
    virtual_server_ip: 172.16.3.121
    virtual_server_fqdn: lb.shadowman.dev
  
  tasks:

  - name: Setup provider
    set_fact:
     provider:
      server: "{{ f5_ip }}"
      user: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      validate_certs: "no"

  - name: Set facts if creating appserver
    set_fact:
      pool_name: app_pool
      virtual_server_name: poolapp
      virtual_server_ip: 172.16.3.122
      virtual_server_fqdn: f5lb.shadowman.dev
    when: inventory_hostname is match("appserver.*")
  
  - name: Create Nodes
    bigip_node:
      provider: "{{ provider }}"
      host: "{{ ansible_host }}"
      name: "{{ inventory_hostname }}"
      monitors:
        - /Common/icmp
        - /Common/https_443
    delegate_to: localhost

  - name: Create Pool
    bigip_pool:
      provider: "{{ provider }}"
      name: "{{ pool_name }}"
      lb_method: "round-robin"
      monitors: 
        - "/Common/https_443"
      monitor_type: "and_list"
    delegate_to: localhost

  - name: Add Pool Members
    bigip_pool_member:
      provider: "{{ provider }}"
      state: "present"
      host: "{{ ansible_host }}"
      name: "{{ inventory_hostname }}"
      port: "443"
      pool: "{{ pool_name }}"
    delegate_to: localhost

  - name: Add Virtual Server
    bigip_virtual_server:
      provider: "{{ provider }}"
      name: "{{ virtual_server_name }}"
      destination: "{{ virtual_server_ip }}"
      port: "443"
      enabled_vlans: "all"
      pool: "{{ pool_name }}"
      snat: "Automap"
    delegate_to: localhost
    notify: IDM_update

  - name: Save Running Config
    bigip_config:
      provider: "{{ provider }}"
      save: yes
    delegate_to: localhost

  - name: Set stats for the e-mail body and ServiceNow
    set_stats:
      data:
        email_body: "{{ email_body }} Load Balancer: https://{{ virtual_server_fqdn }}"
        work_notes: "{{ work_notes }} [code]<a href='https://{{ virtual_server_fqdn }}'>Load Balancer</a>[/code]"
    when: email_body is defined

  handlers:
    - name: IDM_update      
      ipa_host:
        name: "{{ virtual_server_fqdn }}"
        ip_address: "{{ virtual_server_ip }}"
        ipa_pass: "{{ IPA_PASS }}"
        ipa_host: "{{ IPA_HOST }}"
        ipa_user: "{{ IPA_USER }}"
        state: present
        force: yes
      delegate_to: localhost
      no_log: true
      become: no