- name: Device Backup
  hosts: os_cisco
  gather_facts: false
  
  roles:
    - network_backup_git_collection

- name: Create Tower Restore Job
  hosts: aap.shadowman.dev
  gather_facts: no

  roles:
    - network_create_restore