- name: Device Backup
  hosts: all
  gather_facts: false
  collections:
    - vyos.vyos
    - cisco.ios
    - arista.eos

  tasks:

  - name: Backup vyos
    block:
      - name: Backup vyos device
        vyos.vyos.vyos_config:
          backup: yes
          backup_options:
            filename: "{{ inventory_hostname }}.cfg"
            dir_path: /home/network

      - name: REMOVE encrypted password
        lineinfile:
          path: "/home/network/{{ inventory_hostname }}.cfg"
          regexp: 'set system login user vyos authentication encrypted-password.*'
          state: absent

      - name: REMOVE plaintext password
        lineinfile:
          path: "/home/network/{{ inventory_hostname }}.cfg"
          regexp: 'set system login user vyos authentication plaintext-password.*'
          state: absent

      - name: Grab vyos interface facts for new backup type
        vyos.vyos.vyos_facts:
          gather_subset: 
            - '!all'
            - '!min'
          gather_network_resources: all

      - name: Backup using resource modules on vyos
        copy:
          content: "{{ ansible_network_resources | to_nice_yaml }}"
          dest: "/home/network/{{ inventory_hostname }}.yml"
    when: ansible_network_os == 'vyos.vyos.vyos'

  - name: Backup ios
    block:
      - name: Backup ios device
        cisco.ios.ios_config:
          backup: yes
          backup_options:
            filename: "{{ inventory_hostname }}.cfg"
            dir_path: /home/network

      - name: REMOVE NON CONFIG LINES - REGEXP
        lineinfile:
          path: "/home/network/{{ inventory_hostname }}.cfg"
          line: "Building configuration..."
          state: absent

      - name: REMOVE NON CONFIG LINES - REGEXP
        lineinfile:
          path: "/home/network/{{ inventory_hostname }}.cfg"
          regexp: 'Current configuration.*'
          state: absent

      - name: REMOVE enable password
        lineinfile:
          path: "/home/network/{{ inventory_hostname }}.cfg"
          regexp: 'enable password.*'
          state: absent

      - name: REMOVE username and password
        lineinfile:
          path: "/home/network/{{ inventory_hostname }}.cfg"
          regexp: 'username.*'
          state: absent

      - name: Grab ios interface facts for new backup type
        cisco.ios.ios_facts:
          gather_subset:
            - '!all'
            - '!min'
          gather_network_resources: '!vlans'

      - name: Backup using resource modules on ios
        copy:
          content: "{{ ansible_network_resources | to_nice_yaml }}"
          dest: "/home/network/{{ inventory_hostname }}.yml"
    when: ansible_network_os == 'cisco.ios.ios'


  - name: Backup eos
    block:
      - name: Backup eos device
        arista.eos.eos_config:
          backup: yes
          backup_options:
            filename: "{{ inventory_hostname }}.cfg"
            dir_path: /home/network
      
      - name: REMOVE username and password
        lineinfile:
          path: "/home/network/{{ inventory_hostname }}.cfg"
          regexp: 'username.*'
          state: absent

      - name: REMOVE enable name
        lineinfile:
          path: "/home/network/{{ inventory_hostname }}.cfg"
          regexp: 'enable.*'
          state: absent

      - name: Grab eos interface facts for new backup type
        arista.eos.eos_facts:
          gather_subset:
            - '!all'
            - '!min'
          gather_network_resources: all

      - name: Backup using resource modules on eos
        copy:
          content: "{{ ansible_network_resources | to_nice_yaml }}"
          dest: "/home/network/{{ inventory_hostname }}.yml"
    when: ansible_network_os == 'arista.eos.eos'