---
- name: Device Backup
  hosts: os_cisco
  serial: 1
  gather_facts: false

  roles:
    - network_backup_git_collection

- name: Create Controller Restore Job
  hosts: os_cisco
  gather_facts: false

  roles:
    - network_create_restore_collection
