- name: Device Backup
  hosts: tag_Router
  gather_facts: false
  
  roles:
    - network_backup

- name: Copy backup to host
  hosts: report.shadowman.dev
  gather_facts: false
  
  tasks:

  - name: copy files to managed host
    ansible.builtin.copy:
      src: /home/network/
      dest: /home/network/
