- name: Gather facts for devices
  hosts: tag_Router
  gather_facts: false
  
  roles:
    - network_facts_gather

- name: Build report with facts
  hosts: report.shadowman.dev
  gather_facts: no
  tasks:

    - name: build a report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_network