- name: Build Networking Device Report
  hosts: all
  gather_facts: false

  roles:
    - network_facts_gather

  tasks:

    - name: Build the report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_network
        apply:
          delegate_to: report.shadowman.dev
          run_once: true
