- name: Find newest file
  hosts: report.shadowman.dev
  gather_facts: false

  tasks:

    - name: copy files to managed host
      find:
        paths: /home/network
        patterns: "rtr*"
        recurse: true
      register: files_matched

    - name: test
      set_fact:
        latest_files: "{{ files_matched.files | sort(attribute='mtime', reverse=true) }}"

    - name: debug
      debug:
        var: latest_files
