- name: Find newest file
  hosts: report.shadowman.dev
  gather_facts: false

  tasks:

    - name: Find pattern
      find:
        paths: /home/network
        patterns: "java-1.8.0-openjdk-1.8.0.*"
        recurse: true
      register: files_matched

    - name: Find most recently created
      set_fact:
        latest_files: "{{ files_matched.files | sort(attribute='path', reverse=true) | first }}"

    - name: Output
      debug:
        var: latest_files.path
