- name: Find newest file
  hosts: report.shadowman.dev
  gather_facts: false

  tasks:

    - name: Find pattern
      find:
        paths: /home/network
        patterns: "temp*"
        recurse: true
        file_type: directory
      register: files_matched

    - name: Find most recently created
      set_fact:
        latest_files: "{{ files_matched.files | sort(attribute='mtime', reverse=true) | first }}"

    - name: Output 
      debug:
        var: latest_files.path
