# - name: Device Version and Backup
#  hosts: os_cisco
#  gather_facts: false

#  roles:
#    - network_version
#    - network_backup

# - name: Copy backup to host
#  hosts: report.shadowman.dev
#  gather_facts: false

#  tasks:
#
#    - name: copy files to managed host
#      ansible.builtin.copy:
#        src: /tmp/home/network/
#        dest: /home/network/

- name: Test removing pylibssh
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Remove pylibssh
      ansible.builtin.pip:
        name:
          - ansible-pylibssh
        state: absent

    - name: Add paramiko
      ansible.builtin.pip:
        name:
          - paramiko
        state: present

- name: Upgrade and Verify Device Version
  hosts: os_cisco
  gather_facts: false

  roles:
    - network_ios_upgrade
    - network_version
