---
- name: Push Base config using resource modules and vars
  hosts: all
  gather_facts: false
  collections:
    - vyos.vyos
    - cisco.ios
    - arista.eos

  tasks:

  - name: Configure vyos
    block:
      - name: Load stored vars for vyos
        ansible.builtin.include_vars:
          file: vars/vyos_base_config.json
          name: ansible_network_resources

      - name: Configure hostname on vyos
        vyos.vyos.vyos_system:
          host_name: "{{ inventory_hostname }}"

      - name: Push base l3 interfaces to vyos
        vyos.vyos.vyos_l3_interfaces:
          state: overridden
          config: "{{ ansible_network_resources['l3_interfaces'] }}"

      - name: Push base interfaces to vyos
        vyos.vyos.vyos_interfaces:
          state: overridden
          config: "{{ ansible_network_resources['interfaces'] }}"

      - name: Push base firewall global attributes configuration to vyos
        vyos.vyos.vyos_firewall_global:
          config: "{{ ansible_network_resources['firewall_global'] }}"
          state: replaced

      - name: Push base firewall rules to vyos
        vyos.vyos.vyos_firewall_rules:
          state: overridden
          config: "{{ ansible_network_resources['firewall_rules'] }}"

      - name: Push base firewall interfaces to vyos
        vyos.vyos.vyos_firewall_interfaces:
          state: overridden
          config: "{{ ansible_network_resources['firewall_interfaces'] }}"

      - name: Push base lldp global to vyos
        vyos.vyos.vyos_lldp_global:
          state: replaced
          config: "{{ ansible_network_resources['lldp_global'] }}"

      - name: Push base ospfv2 routes attributes configuration to vyos
        vyos.vyos.vyos_ospfv2:
          config: "{{ ansible_network_resources['ospfv2'] }}"
          state: replaced

      - name: Push base ospfv3 routes attributes configuration to vyos
        vyos.vyos.vyos_ospfv3:
          config: "{{ ansible_network_resources['ospfv3'] }}"
          state: replaced
    when: ansible_network_os == 'vyos.vyos.vyos'
    

  - name: Configure ios
    block:
      - name: Load stored vars for ios
        ansible.builtin.include_vars:
          file: vars/ios_base_config.json
          name: ansible_network_resources

      - name: Configure hostname on ios
        cisco.ios.ios_system:
          hostname: "{{ inventory_hostname }}"

      - name: Update l3 interfaces on ios
        cisco.ios.ios_l3_interfaces:
          state: overridden
          config: "{{ ansible_network_resources['l3_interfaces'] }}"

      - name: Update interfaces on ios
        cisco.ios.ios_interfaces:
          state: overridden
          config: "{{ ansible_network_resources['interfaces'] }}"

      - name: Update lldp global on ios
        cisco.ios.ios_lldp_global:
          state: replaced
          config: "{{ ansible_network_resources['lldp_global'] }}"
          
      - name: Update lacp interfaces on ios
        cisco.ios.ios_lacp_interfaces:
          config: "{{ ansible_network_resources['lacp_interfaces'] }}"    
          state: overridden

      - name: Set base static_routes on ios
        cisco.ios.ios_static_routes:
          config: "{{ ansible_network_resources['static_routes'] }}"    
          state: overridden
    when: ansible_network_os == 'cisco.ios.ios'

  - name: Configure eos
    block:

      - name: Load stored vars for eos
        ansible.builtin.include_vars:
          file: vars/eos_base_config.json
          name: ansible_network_resources

      - name: Configure hostname on eos
        arista.eos.eos_system:
          hostname: "{{ inventory_hostname }}"

      - name: Configure VLAN on eos
        arista.eos.eos_vlans: 
          state: overridden
          config: "{{ ansible_network_resources['vlans'] }}"
  
      - name: Update l3 interfaces on eos
        arista.eos.eos_l3_interfaces:
          state: overridden
          config: "{{ ansible_network_resources['l3_interfaces'] }}"

      - name: Update l2 interfaces on eos
        arista.eos.eos_l2_interfaces:
          state: overridden
          config: "{{ ansible_network_resources['l2_interfaces'] }}"
          
      - name: Update interfaces on eos
        arista.eos.eos_interfaces:
          state: overridden
          config: "{{ ansible_network_resources['interfaces'] }}"
          
    when: ansible_network_os == 'arista.eos.eos'