---
- name: Push Base config using resource modules and vars
  hosts: all
  gather_facts: false
  collections:
    - cisco.ios

  tasks:  

    - name: Load stored vars for ios
      include_vars:
        file: vars/ios_base_config.json
        name: ansible_network_resources

    - name: Configure hostname on ios
      cisco.ios.ios_system:
        hostname: "{{ inventory_hostname }}"

    - name: Update l3 interfaces on ios
      cisco.ios.ios_l3_interfaces:
        state: overridden
        config: "{{ ansible_network_resources['l3_interfaces'] }}"

    - name: Update interfaces on ios
      cisco.ios.ios_interfaces:
        state: overridden
        config: "{{ ansible_network_resources['interfaces'] }}"

    - name: Update lldp global on ios
      cisco.ios.ios_lldp_global:
        state: replaced
        config: "{{ ansible_network_resources['lldp_global'] }}"
        
    - name: Update lacp interfaces on ios
      cisco.ios.ios_lacp_interfaces:
        config: "{{ ansible_network_resources['lacp_interfaces'] }}"    
        state: overridden

    - name: Set base static_routes on ios
      cisco.ios.ios_static_routes:
        config: "{{ ansible_network_resources['static_routes'] }}"    
        state: overridden