---
- name: Push Base config using resource modules and vars
  hosts: all
  gather_facts: false
  collections:
    - cisco.ios

  tasks:  

    - name: Load stored vars for ios
      include_vars:
        file: vars/eos_base_config.json
        name: ansible_network_resources

    - name: Configure hostname on ios
      cisco.ios.ios_system:
        hostname: "{{ inventory_hostname }}"

    - name: Update l2 interfaces on ios
      cisco.ios.ios_l2_interfaces:
        state: overridden
        config: "{{ ansible_network_resources['l2_interfaces'] }}"

    