---
- name: Grab Cisco ios facts
  cisco.ios.ios_facts:
    gather_subset: 'min'
    gather_network_resources: all
  register: iosfacts

- name: Display ios Facts
  ansible.builtin.debug:
    var: iosfacts