---
- name: Gather IOS Facts
  ansible.builtin.include_tasks: ios.yml
  when: ansible_network_os == 'cisco.ios.ios'

- name: Gather EOS Facts
  ansible.builtin.include_tasks: eos.yml
  when: ansible_network_os == 'arista.eos.eos'

- name: Gather VYOS Facts
  ansible.builtin.include_tasks: vyos.yml
  when: ansible_network_os == 'vyos.vyos.vyos'
