---
- name: Set vm_name
  ansible.builtin.set_fact:
    vm_name: cluster_name
  when: cluster_name is define

- name: API IDM_update
  community.general.ipa_dnsrecord:
    record_name: api.{{ vm_name }}.apps.hypershift
    record_type: 'A'
    record_value: "{{ apiip | default(omit) }}"
    zone_name: "shadowman.dev."
    ipa_pass: "{{ IPA_PASS }}"
    ipa_host: "{{ IPA_HOST }}"
    ipa_user: "{{ IPA_USER }}"
    state: "{{ record_state | default('present') }}"
  when: apiip is defined

- name: Worker Node IDM_update
  community.general.ipa_dnsrecord:
    record_name: '*.apps.{{ vm_name }}.apps.hypershift'
    record_type: 'A'
    record_value: "{{ workerip | default(omit) }}"
    zone_name: "shadowman.dev."
    ipa_pass: "{{ IPA_PASS }}"
    ipa_host: "{{ IPA_HOST }}"
    ipa_user: "{{ IPA_USER }}"
    state: "{{ record_state | default('present') }}"
  when: workerip is defined
