---
- name: IDM_update
  community.general.ipa_host:
    name: api.{{ vm_name }}.apps.hypershift
    ip_address: "{{ apiip }}"
    ipa_pass: "{{ IPA_PASS }}"
    ipa_host: "{{ IPA_HOST }}"
    ipa_user: "{{ IPA_USER }}"
    state: present
    force: true
