---
- name: IDM_update
  community.general.ipa_dnsrecord:
    record_name: api.{{ vm_name }}.apps.hypershift
    record_type: 'A'
    record_value: "{{ apiip }}"
    zone_name: "shadowman.dev."
    ipa_pass: "{{ IPA_PASS }}"
    ipa_host: "{{ IPA_HOST }}"
    ipa_user: "{{ IPA_USER }}"
    state: present
