---
- name: Backup eos device
  arista.eos.eos_config:
    backup: yes
    backup_options:
      filename: "{{ inventory_hostname }}.cfg"
      dir_path: /tmp/home/network

- name: REMOVE username and password
  ansible.builtin.lineinfile:
    path: "/tmp/home/network/{{ inventory_hostname }}.cfg"
    regexp: 'username.*'
    state: absent

- name: REMOVE enable name
  ansible.builtin.lineinfile:
    path: "/tmp/home/network/{{ inventory_hostname }}.cfg"
    regexp: 'enable.*'
    state: absent

- name: Grab eos interface facts for new backup type
  arista.eos.eos_facts:
    gather_subset:
      - '!all'
      - '!min'
    gather_network_resources: all

- name: Backup using resource modules on eos
  ansible.builtin.copy:
    content: "{{ ansible_network_resources | to_nice_yaml }}"
    dest: "/tmp/home/network/{{ inventory_hostname }}.yml"
  