---
- name: Backup ios device
  cisco.ios.ios_config:
    backup: yes
    backup_options:
      filename: "{{ inventory_hostname }}.cfg"
      dir_path: /home/network

- name: REMOVE NON CONFIG LINES - REGEXP
  ansible.builtin.lineinfile:
    path: "/home/network/{{ inventory_hostname }}.cfg"
    line: "Building configuration..."
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  ansible.builtin.lineinfile:
    path: "/home/network/{{ inventory_hostname }}.cfg"
    regexp: 'Current configuration.*'
    state: absent

- name: REMOVE enable password
  ansible.builtin.lineinfile:
    path: "/home/network/{{ inventory_hostname }}.cfg"
    regexp: 'enable password.*'
    state: absent

- name: REMOVE username and password
  ansible.builtin.lineinfile:
    path: "/home/network/{{ inventory_hostname }}.cfg"
    regexp: 'username.*'
    state: absent

- name: Grab ios interface facts for new backup type
  cisco.ios.ios_facts:
    gather_subset:
      - '!all'
      - '!min'
    gather_network_resources: '!vlans'

- name: Backup using resource modules on ios
  ansible.builtin.copy:
    content: "{{ ansible_network_resources | to_nice_yaml }}"
    dest: "/home/network/{{ inventory_hostname }}.yml"