---
- include_tasks: ios.yml
  when: ansible_network_os == 'cisco.ios.ios'

- include_tasks: eos.yml
  when: ansible_network_os == 'arista.eos.eos'

- include_tasks: vyos.yml
  when: ansible_network_os == 'vyos.vyos.vyos'