---
- name: Grab Arista interface facts
  arista.eos.eos_facts:
    gather_subset: min
    gather_network_resources: interfaces
  
- name: Push the network interfaces to eos
  arista.eos.eos_interfaces:
    config: "{{ ansible_network_resources['interfaces'] }}"
  register: result

- name: Verify that the config did not change as expected
  ansible.builtin.assert:
    that: not result.changed