acl_interfaces:
-   name: Ethernet1
-   name: Ethernet2
interfaces:
-   description: This is configured by Ansible
    enabled: true
    name: Ethernet1
-   description: This is configured by Ansible
    enabled: true
    name: Ethernet2
l2_interfaces:
-   name: Ethernet1
    trunk:
        native_vlan: 20
-   access:
        vlan: 30
    name: Ethernet2
l3_interfaces:
-   ipv4:
    -   address: 192.16.8.190/28
    name: Ethernet1
-   ipv4:
    -   address: 192.16.7.190/28
    name: Ethernet2
lacp: {}
lag_interfaces: []
lldp_global: {}
ospf_interfaces:
-   name: Ethernet1
-   name: Ethernet2
ospfv2: {}
ospfv3: []
vlans:
-   name: Desktop
    state: active
    vlan_id: 20
-   name: Server
    state: active
    vlan_id: 30