---
- name: "Fetch interface state and parse with pyats"
  ansible.utils.cli_parse:
    command: show interfaces
    parser:
      name: ansible.netcommon.pyats
  register: pyats_show_interfaces

- name: print structured interface state data
  ansible.builtin.debug:
    msg: "{{ pyats_show_interfaces['parsed'] }}"