---
- name: Sync with Gitrepo
  ansible.builtin.git:
    repo: git@github.com:shadowman-lab/Ansible-Networkingbackup.git
    dest: /tmp/home/network
    version: main
    accept_newhostkey: true
    key_file: "{{ cert_key_file }}"
  delegate_to: localhost
  run_once: true

- name: Restore ios device
  cisco.ios.ios_config:
    src: /tmp/home/network/cisco_backup/{{ inventory_hostname }}/{{ rollback_date }}
