---
- name: Sync with Gitrepo
  ansible.builtin.git:
    repo: git@github.com:shadowman-lab/Ansible-Networkingbackup.git
    dest: /tmp/home/network
    version: main
    accept_newhostkey: true
    key_file: "{{ cert_key_file }}"
  delegate_to: localhost
  become: false
  run_once: true

- name: Restore ios device
  cisco.ios.ios_config:
    src: /tmp/home/network/cisco_backup/{{ inventory_hostname }}/{{ rollback_date }}
  when: ansible_network_os == 'cisco.ios.ios'

- name: Restore eos device
  arista.eos.eos_config:
    src: /tmp/home/network/arista_backup/{{ inventory_hostname }}/{{ rollback_date }}
  when: ansible_network_os == 'arista.eos.eos'

- name: Restore vyos device
  vyos.vyos.vyos_config:
    src: /tmp/home/network/vyos_backup/{{ inventory_hostname }}/{{ rollback_date }}
  when: ansible_network_os == 'vyos.vyos.vyos'
