---
- name: Find Current Backups
  ansible.builtin.find:
    paths: /tmp/home/network/cisco_backup/{{ inventory_hostname }}
  register: backups
  delegate_to: localhost
  run_once: true

- name: Create Restore Job Template
  ansible.controller.job_template:
    name: Network Restore
    job_type: run
    inventory: Network Inventory
    project: SSP Networking Project
    playbook: network_restore.yml
    credentials:
      - Cisco Credentials
      - Arista Credential
      - VYOS Credentials
      - Alex SSH Git Credential
    limit: os_cisco
    survey_enabled: true
    become_enabled: true
    survey_spec: "{{ lookup('template', 'templates/backup.j2') }}"
  run_once: true
  delegate_to: localhost
