---
- name: Find Current Backups
  ansible.builtin.find:
    paths: /tmp/home/network/backup
  register: backups
  run_once: true
  become: true

- name: Create Restore Job Template
  ansible.controller.job_template:
    name: "Network Restore"
    job_type: "run"
    inventory: "Network Inventory"
    project: "SSP Networking Project"
    playbook: "network_restore.yml"
    credentials:
      - "Cisco Credentials"
      - "VYOS Credentials"
      - "Arista Credential"
    limit: "os_cisco"
    survey_enabled: true
    become_enabled: true
    survey_spec: "{{ lookup('template', 'templates/backup.j2') }}"
